### PR TITLE
CKAN upgrade

### PR DESCRIPTION
**Pull request by alycejenni**
- standardised formatting
- converted string literals to unicode
- standardised docstrings + added some missing ones
- fixed _most_ imports in line with CKAN suggestions for best practice + upgrading to flask
- added travis + coveralls

things I have not done:
- made any real functional changes

**DO NOT MERGE THIS YET**

### CODE REVIEW

**Comment by ashleysommer** [comment]
@alycejenni 
CKAN 2.8.0 was released yesterday.
The current release version of ckanext-ldap does not work correctly on v2.8.0.
Is it safe to use the changes in @ckan-upgrade-2.8.0a branch?
Do you know when this PR might be merged in?

**Comment by alycejenni** [comment]
@ashleysommer I can't give you a good estimate of when we're going to merge it in at the moment - it's part of a big upgrade project so unfortunately it's dependent on a lot of other repositories.

_However_, you should be okay to use the branch! There may be a couple of recent commits that haven't made it across from master yet, but overall the LDAP functionality should be the same. Let me know if you run into any problems with the new branch. :slightly_smiling_face:

**Comment by ashleysommer** [comment]
I tried this yesterday, with some success.
I've found two bugs in CKAN v2.8.0 that are preventing this plugin from working correctly, and I have written patches and submitted PRs to CKAN.
https://github.com/ckan/ckan/pull/4248
https://github.com/ckan/ckan/pull/4249

After those two are merged, into CKAN (hopefully for release in 2.8.1), then ckanext-ldap should work.
My working deployment has both of those patches manually applied and appears to be working correctly.

**Comment by stefina** [comment]
Thank you for this! 
FYI: Including these changes to current master and making sure our CKAN 2.8.2 includes the changes made in this PR: https://github.com/ckan/ckan/pull/4491 the LDAP-Authentication works for us.

**Pull request merged**
